In [25]:
from yahoofinancials import YahooFinancials
import pandas as pd
import numpy as np

ticker = 'LW'
yahoo_financials = YahooFinancials(ticker)

In [26]:
balance_sheet_data_qt = yahoo_financials.get_financial_stmts('annual', 'balance')

In [27]:
list = balance_sheet_data_qt['balanceSheetHistory'][ticker]

In [28]:
my_dictZero = list[0][next(iter(list[0]))]      
columnZero = []
for key in my_dictZero.keys():
    columnZero.append(key)

In [29]:
my_dictOne = list[1][next(iter(list[1]))]      
columnOne = []
for key in my_dictOne.keys():
    columnOne.append(key)

In [30]:
my_dictTwo = list[2][next(iter(list[2]))]      
columnTwo = []
for key in my_dictTwo.keys():
    columnTwo.append(key)

In [31]:
my_dictThree = list[3][next(iter(list[3]))]      
columnThree = []
for key in my_dictThree.keys():
    columnThree.append(key)

In [32]:
orderedKeysZero = []
for index in range(len(columnOne)):
    if(columnOne[index] not in columnZero):
        try:
            orderedKeysZero.append(columnZero[index])
        except IndexError:
            pass
        orderedKeysZero.append(columnOne[index])
    else:
        try:
            orderedKeysZero.append(columnZero[index])
        except IndexError:
            pass
        
orderedKeysOne = []
for index in range(len(columnTwo)):
    if(columnTwo[index] not in orderedKeysZero):
        try:
            orderedKeysOne.append(orderedKeysZero[index])
        except IndexError:
            pass
        orderedKeysOne.append(columnTwo[index])
    else:
        try:
            orderedKeysOne.append(orderedKeysZero[index])
        except IndexError:
            pass
        
orderedKeysTwo = []
for index in range(len(columnThree)):
    if(columnTwo[index] not in orderedKeysOne):
        try:
            orderedKeysTwo.append(orderedKeysOne[index])
        except IndexError:
            pass
        orderedKeysTwo.append(columnThree[index])
    else:
        try:
            orderedKeysTwo.append(orderedKeysOne[index])
        except IndexError:
            pass

In [33]:
df2 = pd.DataFrame()
for i in range(len(list)):
    df = pd.DataFrame.from_dict(list[i], orient = 'index')
    df = df.T
    df2 = pd.concat([df2, df], axis=1, sort=False)

In [34]:
sorter = orderedKeysTwo

In [36]:
df3 = df2.reindex(sorter)
df3

,2018-05-27,2017-05-28,2016-05-29,2015-05-31
intangibleAssets,3.540000e+07,3.720000e+07,3.960000e+07,4.170000e+07
totalLiab,3.031800e+09,3.082100e+09,7.103000e+08,6.568000e+08
totalStockholderEquity,-3.348000e+08,-6.472000e+08,1.400600e+09,1.357500e+09
minorityInterest,5.560000e+07,5.070000e+07,4.740000e+07,4.160000e+07
otherCurrentLiab,3.110000e+07,3.210000e+07,NaN,NaN
totalAssets,2.752600e+09,2.485600e+09,2.158300e+09,2.055900e+09
commonStock,1.464000e+08,1.461000e+08,1.409800e+09,1.362600e+09
otherCurrentAssets,NaN,NaN,2.000000e+06,3.400000e+06
retainedEarnings,4.264000e+08,1.210000e+08,NaN,NaN
otherLiab,1.764000e+08,1.617000e+08,1.961000e+08,1.811000e+08
goodWill,1.351000e+08,1.330000e+08,1.339000e+08,1.349000e+08
treasuryStock,-9.076000e+08,-9.143000e+08,-9.200000e+06,-5.100000e+06
otherAssets,1.110000e+07,7.400000e+06,6.500000e+06,1.263000e+08
cash,5.560000e+07,5.710000e+07,3.640000e+07,3.060000e+07
totalCurrentLiabilities,5.187000e+08,5.554000e+08,4.096000e+08,3.892000e+08
deferredLongTermAssetCharges,4.000000e+05,5.000000e+05,2.200000e+06,NaN
shortLongTermDebt,3.530000e+07,3.790000e+07,1.350000e+07,3.920000e+07
otherStockholderEquity,-9.047000e+08,-9.141000e+08,-9.200000e+06,-5.100000e+06
propertyPlantEquipment,1.420800e+09,1.271200e+09,1.043100e+09,1.001300e+09
totalCurrentAssets,9.304000e+08,8.582000e+08,7.800000e+08,7.517000e+08
longTermInvestments,2.198000e+08,1.786000e+08,1.552000e+08,NaN
netTangibleAssets,-5.053000e+08,-8.174000e+08,1.227100e+09,1.180900e+09